# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-07 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='url',
            field=models.URLField(null=True, verbose_name='访问地址'),
        ),
        migrations.AddField(
            model_name='subarea',
            name='url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=20, verbose_name='城市名称'),
        ),
    ]
