# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-07 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdata', '0002_auto_20171007_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(max_length=20, verbose_name='区域名称'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='城市名称'),
        ),
        migrations.AlterField(
            model_name='subarea',
            name='name',
            field=models.CharField(max_length=30, verbose_name='子区域名称'),
        ),
        migrations.AlterUniqueTogether(
            name='area',
            unique_together=set([('city', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='subarea',
            unique_together=set([('area', 'name')]),
        ),
    ]
