# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-07 08:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hdata', '0003_auto_20171007_0835'),
    ]

    operations = [
        migrations.CreateModel(
            name='LjSecondChengjiaoRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.IntegerField()),
                ('position_info', models.CharField(max_length=200)),
                ('subarea', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=200)),
                ('deal_date', models.DateField()),
                ('info', models.CharField(max_length=200)),
                ('source', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('unit_price', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name': '二手房行政区域'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': '城市'},
        ),
        migrations.AlterModelOptions(
            name='subarea',
            options={'verbose_name': '二手房子区域'},
        ),
        migrations.AlterField(
            model_name='area',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hdata.City', verbose_name='城市'),
        ),
    ]
