# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-07 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdata', '0004_auto_20171007_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ljsecondchengjiaorecord',
            name='total_price',
            field=models.FloatField(),
        ),
    ]
