# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-07 10:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hdata', '0006_auto_20171007_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='PullPageStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('finish_time', models.DateTimeField(null=True)),
                ('success_count', models.IntegerField(default=0)),
                ('total_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '拉取页面状态表',
            },
        ),
        migrations.CreateModel(
            name='PullStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('total_pages', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(null=True)),
                ('subarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hdata.SubArea')),
            ],
            options={
                'verbose_name': '拉取状态表',
            },
        ),
        migrations.AddField(
            model_name='pullpagestatus',
            name='pull',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hdata.PullStatus'),
        ),
        migrations.AlterUniqueTogether(
            name='pullstatus',
            unique_together=set([('subarea', 'type', 'start_time')]),
        ),
        migrations.AlterUniqueTogether(
            name='pullpagestatus',
            unique_together=set([('pull', 'url')]),
        ),
    ]
