# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 08:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hdata', '0007_auto_20171007_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='LjSecondChengjiao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField()),
                ('deal_date', models.DateField()),
                ('source', models.CharField(max_length=200)),
                ('xiaoqu', models.CharField(max_length=100, verbose_name='小区名')),
                ('bedroom_num', models.IntegerField(default=-1, verbose_name='室')),
                ('meetingroom_num', models.IntegerField(default=-1, verbose_name='厅')),
                ('space', models.FloatField(verbose_name='面积（平方米）')),
                ('floor_num', models.IntegerField(default=-1, verbose_name='总层数')),
                ('produce_date', models.DateField(null=True, verbose_name='建筑日期')),
                ('produce_type', models.CharField(max_length=100, verbose_name='建筑类型')),
                ('elevator', models.BooleanField(verbose_name='有电梯')),
                ('orientation', models.CharField(max_length=10, verbose_name='朝向')),
                ('other_info', models.CharField(max_length=100, verbose_name='其他信息')),
                ('unit_price', models.IntegerField()),
                ('subarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hdata.SubArea')),
            ],
            options={
                'verbose_name': '链家二手房成交记录',
            },
        ),
        migrations.AlterUniqueTogether(
            name='ljsecondchengjiao',
            unique_together=set([('unit_price', 'space', 'deal_date', 'subarea', 'xiaoqu')]),
        ),
    ]
