# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdata', '0008_auto_20171009_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ljsecondchengjiao',
            name='produce_date',
            field=models.IntegerField(null=True, verbose_name='建筑年份'),
        ),
    ]
