# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdata', '0009_auto_20171009_1624'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ljsecondchengjiao',
            options={'verbose_name': '链家二手房成交表'},
        ),
        migrations.AlterField(
            model_name='ljsecondchengjiao',
            name='elevator',
            field=models.IntegerField(default=-1, verbose_name='电梯'),
        ),
    ]
